// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  physicalAISidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/physical-ai-embodied-intelligence',
      ],
    },
    {
      type: 'category',
      label: 'Fundamentals',
      items: [
        'fundamentals/humanoid-robotics',
      ],
    },
    {
      type: 'category',
      label: 'Kinematics and Dynamics',
      items: [
        'kinematics/kinematics-dynamics',
      ],
    },
    {
      type: 'category',
      label: 'Perception Systems',
      items: [
        'perception/perception-systems',
      ],
    },
    {
      type: 'category',
      label: 'Control Theory',
      items: [
        'control/control-theory',
      ],
    },
    {
      type: 'category',
      label: 'Machine Learning for Physical AI',
      items: [
        'machine-learning/ml-physical-ai',
      ],
    },
    {
      type: 'category',
      label: 'Future Directions',
      items: [
        'future-directions/future-integration',
      ],
    },
  ],
};

module.exports = sidebars;
