/**
 * Creating a sidebar enables you to: - Create an ordered group of docs
 *   - Show a hierarchy of categories and/or pages
 *   - Show them in the order they appear in the sidebar (and not automatically sort with `position`)
 *
 * To learn more, visit: https://docusaurus.io/docs/sidebar
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.'
  }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post', 'tutorial-basics/create-a-page', 'tutorial-basics/deploy-your-site', 'tutorial-basics/markdown-features'],
    },
  ],
   */
};

module.exports = sidebars;
