import React, { useState } from 'react';
import { useChatContext } from '../contexts/ChatContext';
import { chatApiService } from '../services/chat-api';
import { QueryRequest, Message } from '../types/chat';
import './MessageInput.css';

export const MessageInput: React.FC = () => {
  const [inputValue, setInputValue] = useState('');
  const { state, dispatch } = useChatContext();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!inputValue.trim()) return;

    // Set loading state
    dispatch({ type: 'SET_LOADING', payload: true });
    dispatch({ type: 'SET_CURRENT_QUERY', payload: inputValue });
    dispatch({ type: 'SET_ERROR', payload: null });

    try {
      // Add user message to the chat
      const userMessage: Message = {
        id: `msg-${Date.now()}`,
        content: inputValue,
        sender: 'user',
        timestamp: new Date(),
      };
      dispatch({ type: 'ADD_MESSAGE', payload: userMessage });

      // Prepare the query request
      const request: QueryRequest = {
        query: inputValue,
        context: state.selectedText || null,
        sessionId: null, // Will be generated by backend
      };

      // Call the API - if selected text context exists, use selected text query endpoint
      let response;
      if (state.selectedText) {
        response = await chatApiService.querySelectedText(request);
      } else {
        response = await chatApiService.queryFullBook(request);
      }

      // Add assistant response to the chat
      const assistantMessage: Message = {
        id: `msg-${Date.now() + 1}`,
        content: response.response,
        sender: 'assistant',
        timestamp: new Date(response.timestamp),
        sources: response.sources.map(source => ({
          title: source.title,
          url: source.url,
          content: source.content,
          confidence: source.score
        }))
      };
      dispatch({ type: 'ADD_MESSAGE', payload: assistantMessage });

      // Clear input
      setInputValue('');
    } catch (error) {
      console.error('Error sending message:', error);
      dispatch({
        type: 'SET_ERROR',
        payload: error instanceof Error ? error.message : 'Failed to send message'
      });
    } finally {
      // Reset loading state
      dispatch({ type: 'SET_LOADING', payload: false });
      dispatch({ type: 'SET_CURRENT_QUERY', payload: null });
    }
  };

  return (
    <form className="message-input-form" onSubmit={handleSubmit}>
      <div className="message-input-container">
        <input
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder={state.selectedText
            ? "Ask about the selected text..."
            : "Ask a question about the Physical AI & Humanoid Robotics book..."}
          className="message-input"
          disabled={state.isLoading}
        />
        <button
          type="submit"
          className="message-send-button"
          disabled={state.isLoading || !inputValue.trim()}
        >
          Send
        </button>
      </div>
    </form>
  );
};